const state={date:null,time:null};
const calendar=document.getElementById('calendar');const monthLabel=document.getElementById('monthLabel');const times=document.getElementById('times');const timesTitle=document.getElementById('timesTitle');const details=document.getElementById('detailsStep');const calStep=document.getElementById('calendarStep');const success=document.getElementById('successStep');const summary=document.getElementById('selectedSummary');
let cursor=new Date();cursor=new Date(cursor.getFullYear(),cursor.getMonth(),1);
const slots=['9:00 AM','10:30 AM','12:00 PM','1:30 PM','3:00 PM','4:30 PM'];
function fmtDate(d){return d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function render(){calendar.innerHTML='';monthLabel.textContent=cursor.toLocaleDateString('en-US',{month:'long',year:'numeric'});const first=cursor.getDay();const days=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();for(let i=0;i<first;i++){const x=document.createElement('span');calendar.appendChild(x)}const today=new Date();today.setHours(0,0,0,0);for(let d=1;d<=days;d++){const date=new Date(cursor.getFullYear(),cursor.getMonth(),d);const btn=document.createElement('button');btn.className='day';btn.textContent=d;const weekend=[0,6].includes(date.getDay());if(date<today||weekend)btn.disabled=true;if(state.date&&date.toDateString()===state.date.toDateString())btn.classList.add('selected');btn.onclick=()=>{state.date=date;state.time=null;render();renderTimes()};calendar.appendChild(btn)}}
function renderTimes(){times.innerHTML='';if(!state.date){timesTitle.textContent='Select a date to view times';return}timesTitle.textContent=`Available times · ${state.date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}`;slots.forEach(s=>{const b=document.createElement('button');b.className='time-btn';b.textContent=s;if(state.time===s)b.classList.add('selected');b.onclick=()=>{state.time=s;document.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');summary.innerHTML=`<small>YOUR SELECTION</small><strong>${fmtDate(state.date)}<br>${state.time} ET</strong>`;setTimeout(()=>{calStep.classList.add('hidden');details.classList.remove('hidden');document.querySelectorAll('.step-head span')[1].classList.add('active');window.scrollTo({top:document.querySelector('.booking-shell').offsetTop-20,behavior:'smooth'})},180)};times.appendChild(b)})}
document.getElementById('prevMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};document.getElementById('nextMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};document.getElementById('backToCalendar').onclick=()=>{details.classList.add('hidden');calStep.classList.remove('hidden')};
details.addEventListener('submit',async e=>{e.preventDefault();if(!state.date||!state.time)return;const btn=details.querySelector('.submit-btn');btn.disabled=true;btn.innerHTML='Confirming…';const fd=new FormData(details);const payload=Object.fromEntries(fd.entries());payload.date=state.date.toISOString().slice(0,10);payload.dateLabel=fmtDate(state.date);payload.time=state.time;payload.timezone='America/New_York';payload.sessionType='Executive Strategy Session';payload.price=350;payload.source='earlyadvisory.co';try{const r=await fetch('/api/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Booking failed');details.classList.add('hidden');success.classList.remove('hidden');document.querySelectorAll('.step-head span')[2].classList.add('active');document.getElementById('successText').textContent=`Thanks, ${payload.firstName}. Your request has been captured and is ready for the confirmation workflow.`;document.getElementById('confirmationCard').innerHTML=`<div><span>Date</span><strong>${payload.dateLabel}</strong></div><div><span>Time</span><strong>${payload.time} ET</strong></div><div><span>Session</span><strong>${payload.sessionType}</strong></div><div><span>Email</span><strong>${payload.email}</strong></div>`;window.scrollTo({top:document.querySelector('.booking-shell').offsetTop-20,behavior:'smooth'})}catch(err){alert('Something went wrong submitting the appointment. Please try again.');btn.disabled=false;btn.innerHTML='Confirm Strategy Session <span>→</span>'}});
render();renderTimes();