const state={date:null,time:null};
const calendar=document.getElementById('calendar');const monthLabel=document.getElementById('monthLabel');const times=document.getElementById('times');const timesTitle=document.getElementById('timesTitle');const details=document.getElementById('detailsStep');const calStep=document.getElementById('calendarStep');const success=document.getElementById('successStep');const summary=document.getElementById('selectedSummary');
let cursor=new Date();cursor=new Date(cursor.getFullYear(),cursor.getMonth(),1);
const slots=['9:00 AM','10:30 AM','12:00 PM','1:30 PM','3:00 PM','4:30 PM'];
function fmtDate(d){return d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function render(){calendar.innerHTML='';monthLabel.textContent=cursor.toLocaleDateString('en-US',{month:'long',year:'numeric'});const first=cursor.getDay();const days=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();for(let i=0;i<first;i++){calendar.appendChild(document.createElement('span'))}const today=new Date();today.setHours(0,0,0,0);for(let d=1;d<=days;d++){const date=new Date(cursor.getFullYear(),cursor.getMonth(),d);const btn=document.createElement('button');btn.className='day';btn.textContent=d;const weekend=[0,6].includes(date.getDay());if(date<today||weekend)btn.disabled=true;if(state.date&&date.toDateString()===state.date.toDateString())btn.classList.add('selected');btn.onclick=()=>{state.date=date;state.time=null;render();renderTimes()};calendar.appendChild(btn)}}
function renderTimes(){times.innerHTML='';if(!state.date){timesTitle.textContent='Select a date to view times';return}timesTitle.textContent=`Available times · ${state.date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}`;slots.forEach(s=>{const b=document.createElement('button');b.className='time-btn';b.textContent=s;if(state.time===s)b.classList.add('selected');b.onclick=()=>{state.time=s;document.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');summary.innerHTML=`<small>YOUR SELECTION</small><strong>${fmtDate(state.date)}<br>${state.time} ET</strong>`;setTimeout(()=>{calStep.classList.add('hidden');details.classList.remove('hidden');document.querySelectorAll('.step-head span')[1].classList.add('active');document.querySelector('.booking-shell').scrollIntoView({behavior:'smooth',block:'start'})},180)};times.appendChild(b)})}
document.getElementById('prevMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};document.getElementById('nextMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};document.getElementById('backToCalendar').onclick=()=>{details.classList.add('hidden');calStep.classList.remove('hidden')};
details.addEventListener('submit',async e=>{e.preventDefault();if(!state.date||!state.time)return;const btn=details.querySelector('.submit-btn');btn.disabled=true;btn.innerHTML='Confirming…';const fd=new FormData(details);const payload=Object.fromEntries(fd.entries());payload.date=state.date.toISOString().slice(0,10);payload.dateLabel=fmtDate(state.date);payload.time=state.time;payload.timezone='America/New_York';payload.sessionType='Executive Strategy Session';payload.price=600;payload.source=location.hostname;try{const r=await fetch('/api/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Booking failed');details.classList.add('hidden');success.classList.remove('hidden');document.querySelectorAll('.step-head span')[2].classList.add('active');document.getElementById('successText').textContent=`Thanks, ${payload.firstName}. Your request has been captured and is ready for the confirmation workflow.`;document.getElementById('confirmationCard').innerHTML=`<div><span>Date</span><strong>${payload.dateLabel}</strong></div><div><span>Time</span><strong>${payload.time} ET</strong></div><div><span>Session</span><strong>${payload.sessionType}</strong></div><div><span>Price</span><strong>$600</strong></div><div><span>Email</span><strong>${payload.email}</strong></div>`;document.querySelector('.booking-shell').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){alert('Something went wrong submitting the appointment. Please try again.');btn.disabled=false;btn.innerHTML='Confirm Strategy Session <span>→</span>'}});
render();renderTimes();
const footer=document.createElement('footer');footer.className='booking-footer';footer.innerHTML='<div class="booking-footer-inner"><strong>EARLY ADVISORY</strong><span>Financial strategy for the firms building America.</span><a href="/">Back to site</a></div>';document.body.appendChild(footer);
const viewportFix=document.createElement('style');viewportFix.textContent=`html,body{max-width:100%;overflow-x:hidden;overscroll-behavior-y:none}body{min-height:100dvh;display:flex;flex-direction:column}main{flex:1 0 auto}.booking-footer{flex:0 0 auto;border-top:1px solid #173442;background:#06111d;padding:22px max(16px,calc((100% - 1180px)/2)) max(22px,env(safe-area-inset-bottom));margin:0}.booking-footer-inner{display:flex;align-items:center;gap:16px;justify-content:space-between;color:#6f8794;font-size:12px}.booking-footer-inner strong{color:#dce8ed;letter-spacing:.12em}.booking-footer-inner a{color:#67c8aa;text-decoration:none}@media(max-width:600px){.booking-footer-inner{flex-direction:column;align-items:flex-start}.intro{padding-top:18px}.booking-shell{padding-bottom:30px}.scheduler{margin-bottom:0}.summary-card{margin-bottom:0}}`;document.head.appendChild(viewportFix);
const conciergeCss=document.createElement('link');conciergeCss.rel='stylesheet';conciergeCss.href='/concierge.css';document.head.appendChild(conciergeCss);const conciergeScript=document.createElement('script');conciergeScript.src='/concierge.js';conciergeScript.defer=true;document.body.appendChild(conciergeScript);